export const ACHIEVEMENT_DEFINITIONS = [
  {
    achievementId: "first_application",
    title: "First Steps",
    description: "Submit your first job application",
    icon: "🎯",
    category: "applications",
    target: 1,
  },
  {
    achievementId: "centurion",
    title: "Centurion",
    description: "Submit 100 job applications",
    icon: "🏆",
    category: "applications",
    target: 100,
  },
  {
    achievementId: "marathoner",
    title: "Marathoner",
    description: "Submit 300 job applications",
    icon: "🏅",
    category: "applications",
    target: 300,
  },
  {
    achievementId: "code_warrior_100",
    title: "Code Warrior",
    description: "Solve 100 LeetCode problems",
    icon: "⚔️",
    category: "leetcode",
    target: 100,
  },
  {
    achievementId: "algorithm_master",
    title: "Algorithm Master",
    description: "Solve 500 LeetCode problems",
    icon: "🧠",
    category: "leetcode",
    target: 500,
  },
  {
    achievementId: "streak_7",
    title: "On Fire",
    description: "Maintain a 7-day streak",
    icon: "🔥",
    category: "streak",
    target: 7,
  },
  {
    achievementId: "streak_30",
    title: "Unstoppable",
    description: "Maintain a 30-day streak",
    icon: "💫",
    category: "streak",
    target: 30,
  },
  {
    achievementId: "streak_100",
    title: "Legend",
    description: "Maintain a 100-day streak",
    icon: "👑",
    category: "streak",
    target: 100,
  },
  {
    achievementId: "first_project",
    title: "Builder",
    description: "Complete your first project",
    icon: "🔨",
    category: "projects",
    target: 1,
  },
  {
    achievementId: "project_master",
    title: "Project Master",
    description: "Complete 5 projects",
    icon: "🏗️",
    category: "projects",
    target: 5,
  },
  {
    achievementId: "first_interview",
    title: "Interview Ready",
    description: "Complete your first interview",
    icon: "🎤",
    category: "interviews",
    target: 1,
  },
  {
    achievementId: "first_offer",
    title: "Offer Letter",
    description: "Receive your first offer",
    icon: "🎉",
    category: "applications",
    target: 1,
  },
  {
    achievementId: "scholar_100",
    title: "Scholar",
    description: "Complete 100 study hours",
    icon: "📚",
    category: "study",
    target: 100,
  },
  {
    achievementId: "scholar_500",
    title: "Knowledge Seeker",
    description: "Complete 500 study hours",
    icon: "🎓",
    category: "study",
    target: 500,
  },
  {
    achievementId: "networker_50",
    title: "Networker",
    description: "Contact 50 recruiters",
    icon: "🤝",
    category: "networking",
    target: 50,
  },
  {
    achievementId: "journal_30",
    title: "Consistent",
    description: "Write 30 journal entries",
    icon: "📝",
    category: "journal",
    target: 30,
  },
  {
    achievementId: "score_1000",
    title: "Thousand Points",
    description: "Reach a lifetime score of 1,000",
    icon: "🌟",
    category: "score",
    target: 1000,
  },
  {
    achievementId: "score_10000",
    title: "Ten Thousand Points",
    description: "Reach a lifetime score of 10,000",
    icon: "💎",
    category: "score",
    target: 10000,
  },
] as const;
